export const RECIPIENT_POSITIONS = [
  "HR Officer",
  "IT Officer",
  "Finance Manager",
  "Human Resources Manager",
  "Chief Executive Officer",
  "Chief Technology Officer",
  "Managing Director",
  "Administrative Manager",
  "Accountant",
  "Procurement Officer",
  "Operations Manager",
  "Sales Manager",
  "Marketing Manager",
  "Legal Counsel",
  "Company Secretary",
  "Internal Auditor",
  "Risk Manager",
  "Compliance Officer",
  "Facilities Manager",
  "Security Manager",
  "Front Desk Officer",
  "Receptionist",
  "Executive Assistant",
  "Personal Assistant",
  "Office Manager",
  "Administrative Assistant",
  "Clerk",
  "Driver",
  "Messenger",
  "Cleaner",
  "Security Guard",
];